/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.List;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Connection;
import javax.swing.JComboBox;
/**
 *
 * @author sindy
 */
public class Admin extends javax.swing.JFrame {
    /**
     * Creates new form TampilanAwal
     */
    static DefaultTableModel model1 = new DefaultTableModel(new String[]{"Tipe Kamar", "Nama", "Nomor Hp", "Jumlah Orang", "Checkin", "Checkout", "Membership", "Total"}, 0);
    private TB_TambahAdmin Admin = new TB_TambahAdmin();
    private TB_PemesananKamar Pemesanan = new TB_PemesananKamar();
    private TB_Transaksi Transaksi = new TB_Transaksi();
    private DefaultTableModel modeladmin;
    private DefaultTableModel modeltransaksi;
    
    public Admin() {
        initComponents();
        modeladmin = new DefaultTableModel(new String[]{"ID", "Nama", "Role", "Tgl Bergabung"}, 0);
        modeltransaksi = new DefaultTableModel(new String[]{"ID", "ID Pembeli", "Id Admin", "Tgl Transaksi", "Total"}, 0);
        loadDataAdmin();
        loadDataPemesanan(); 
        loadDataTransaksi();
        loadPilihanPembeli();
        loadPilihanAdmin();
        
    TabelAdmin.getSelectionModel().addListSelectionListener(event -> {
        int selectedRow = TabelAdmin.getSelectedRow();
        if (selectedRow != -1) {
            IdAdmin.setText(modeladmin.getValueAt(selectedRow, 0).toString());
            NamaAdmin.setText(modeladmin.getValueAt(selectedRow, 1).toString());
            RoleAdmin.setText(modeladmin.getValueAt(selectedRow, 2).toString());
            TglAdmin.setText(modeladmin.getValueAt(selectedRow, 3).toString());
        }
    });
    
    TabelTransaksi.getSelectionModel().addListSelectionListener(event -> {
        int selectedRow = TabelTransaksi.getSelectedRow();
        if (selectedRow != -1) {
            IdTransaksi.setText(modeltransaksi.getValueAt(selectedRow, 0).toString());
            PilihanNama.setSelectedItem(modeltransaksi.getValueAt(selectedRow, 1).toString());
            PilihanAdmin.setSelectedItem(modeltransaksi.getValueAt(selectedRow, 2).toString());
            TglTransaksi.setText(modeltransaksi.getValueAt(selectedRow, 3).toString());
            TotalPembayaran.setText(modeltransaksi.getValueAt(selectedRow, 4).toString());
            
        }
    });
    
    TabelTransaksi.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            updatePilihan();
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PilihanNama = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        TotalPembayaran = new javax.swing.JTextField();
        ButtonReset = new javax.swing.JButton();
        ButtonTambah = new javax.swing.JButton();
        ButtonEdit = new javax.swing.JButton();
        ButtonHapus = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TglTransaksi = new javax.swing.JTextField();
        PilihanAdmin = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        TabelTransaksi = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        IdTransaksi = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        TglAdmin = new javax.swing.JTextField();
        RoleAdmin = new javax.swing.JTextField();
        NamaAdmin = new javax.swing.JTextField();
        IdAdmin = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelAdmin = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        EditAdmin = new javax.swing.JButton();
        HapusAdmin = new javax.swing.JButton();
        ResetFormAdmin = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelPemesananPembeli = new javax.swing.JTable();
        HapusPemesanan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel1.setText("EasyStay Homestay");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo EasyStay.png"))); // NOI18N

        jLabel4.setText("--------------------------------------------------------------------------------------------------------------------------------------------------");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Pemesanan Kamar Mudah dan Murah");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)))
                .addGap(179, 179, 179))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Data Pembelian dan Data Admin");

        jLabel7.setText("Nama :");

        PilihanNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilihanNamaActionPerformed(evt);
            }
        });

        jLabel8.setText("Total :");

        TotalPembayaran.setEditable(false);
        TotalPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPembayaranActionPerformed(evt);
            }
        });

        ButtonReset.setText("Reset Form");
        ButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResetActionPerformed(evt);
            }
        });

        ButtonTambah.setBackground(new java.awt.Color(219, 237, 255));
        ButtonTambah.setText("TAMBAH");
        ButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahActionPerformed(evt);
            }
        });

        ButtonEdit.setText("Edit");
        ButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditActionPerformed(evt);
            }
        });

        ButtonHapus.setText("Hapus");
        ButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHapusActionPerformed(evt);
            }
        });

        jLabel10.setText("--------------------------------------------------------------------------------------------------------------------------------------------------");

        jLabel16.setText("Nama Admin :");

        jLabel18.setText("Tgl Transaksi");

        PilihanAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilihanAdminActionPerformed(evt);
            }
        });

        TabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama Pembeli", "Tgl Transaksi", "Total", "Admin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(TabelTransaksi);

        jLabel6.setText("ID :");

        IdTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(ButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PilihanAdmin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(IdTransaksi))
                                    .addComponent(PilihanNama, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TotalPembayaran)
                                    .addComponent(TglTransaksi)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(IdTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PilihanNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TotalPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TglTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PilihanAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonReset)
                    .addComponent(ButtonEdit)
                    .addComponent(ButtonHapus)
                    .addComponent(ButtonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10))
        );

        jPanel2.add(jPanel6, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Transkasi", jPanel2);

        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel21.setText("EasyStay Homestay");

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo EasyStay.png"))); // NOI18N

        jLabel23.setText("---------------------------------------------------------------------------------------------------------------------------------------------------");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Pemesanan Kamar Mudah dan Murah");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel24)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel24)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23))
        );

        jPanel9.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel25.setText("-------------------------------------------------------------------------------------------------------------------------------------------------");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText("Tabel Data Admin");

        jLabel27.setText("Id :");

        jLabel28.setText("Nama :");

        jLabel29.setText("Role :");

        jLabel30.setText("Tgl Bergabung :");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setText("Data Admin");

        TabelAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Role", "Tgl Bergabung"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TabelAdmin);

        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        EditAdmin.setText("Edit");
        EditAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditAdminActionPerformed(evt);
            }
        });

        HapusAdmin.setText("Hapus");
        HapusAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusAdminActionPerformed(evt);
            }
        });

        ResetFormAdmin.setText("Reset Form");
        ResetFormAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetFormAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel29)
                                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel27))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(IdAdmin)
                                            .addComponent(NamaAdmin)
                                            .addComponent(RoleAdmin)
                                            .addComponent(TglAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)))
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EditAdmin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(HapusAdmin))))
                            .addComponent(ResetFormAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(IdAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(NamaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(RoleAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(TglAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ResetFormAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(EditAdmin)
                            .addComponent(HapusAdmin)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel25))
        );

        jPanel9.add(jPanel11, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Admin", jPanel9);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel32.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel32.setText("EasyStay Homestay");

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo EasyStay.png"))); // NOI18N

        jLabel34.setText("---------------------------------------------------------------------------------------------------------------------------------------------------");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setText("Pemesanan Kamar Mudah dan Murah");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel35)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel33))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel35)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel34))
        );

        jPanel8.add(jPanel12, java.awt.BorderLayout.PAGE_START);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        jLabel36.setText("---------------------------------------------------------------------------------------------------------------------------------------------------");

        TabelPemesananPembeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "Nomor HP", "Jumlah Orang", "Tgl Check-In", "Tgl Check-Out", "Membership", "Tipe Kamar", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TabelPemesananPembeli);

        HapusPemesanan.setText("Hapus");
        HapusPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusPemesananActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HapusPemesanan)
                .addGap(53, 53, 53))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(HapusPemesanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36))
        );

        jPanel8.add(jPanel13, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Data Pemesanan", jPanel8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String val_id = IdAdmin.getText();
        String val_nama_admin = NamaAdmin.getText();
        String val_role = RoleAdmin.getText();
        String val_tgl_bergabung = TglAdmin.getText();
        
        TambahAdmin admin = new TambahAdmin(
        0,
        val_nama_admin,
        val_role,
        val_tgl_bergabung
        );
        
        try {
            Admin.InsertAdmin(admin);
            loadDataAdmin(); 
            loadPilihanAdmin();
            loadDataTransaksi();
            JOptionPane.showMessageDialog(null, "Data Admin berhasil ditambahkan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat menambahkan data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EditAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditAdminActionPerformed
        // TODO add your handling code here:
        int selectedRow = TabelAdmin.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih Baris yang akan diubah", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Object idValue = modeladmin.getValueAt(selectedRow, 0);
        if (idValue == null || idValue.toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ID tidak valid atau kosong.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int id = Integer.parseInt(idValue.toString());
            String nama = NamaAdmin.getText();
            String role = RoleAdmin.getText();
            String tgl = TglAdmin.getText();

            TambahAdmin editadmin = new TambahAdmin(id, nama, role, tgl);

            try {
                Admin.updateAdmin(editadmin);
                loadDataAdmin();
                loadPilihanAdmin();
                loadDataTransaksi();
                JOptionPane.showMessageDialog(null, "Data berhasil diubah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Tidak dapat mengubah data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            System.out.println("ID tidak valid: " + e.getMessage());
        }
    }//GEN-LAST:event_EditAdminActionPerformed

    private void HapusAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusAdminActionPerformed
        // TODO add your handling code here:
        int selectedRow = TabelAdmin.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Piih baris yang akan dihapus", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = (int) modeladmin.getValueAt(selectedRow, 0);

        try {
            Admin.deleteAdmin(id);
            loadDataAdmin();
            loadDataTransaksi();
            loadPilihanPembeli();
            loadPilihanAdmin();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat menghapus data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_HapusAdminActionPerformed

    private void ResetFormAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetFormAdminActionPerformed
        // TODO add your handling code here:
        IdAdmin.setText("");
        NamaAdmin.setText("");
        RoleAdmin.setText("");
        TglAdmin.setText("");
    }//GEN-LAST:event_ResetFormAdminActionPerformed

    private void HapusPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusPemesananActionPerformed
        // TODO add your handling code here:
        int selectedRow = TabelPemesananPembeli.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih baris yang akan dihapus", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String namaPembeli = model1.getValueAt(selectedRow, 1).toString();

        try {
            Pemesanan.deletePesanan(namaPembeli);
            loadDataPemesanan();
            loadDataTransaksi(); 
            loadPilihanPembeli();
            loadPilihanAdmin();
            
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat menghapus data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_HapusPemesananActionPerformed

    private void ButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahActionPerformed
        // TODO add your handling code here:
        String val_id = IdTransaksi.getText();
        String val_adminid = PilihanAdmin.getSelectedItem() != null ? PilihanAdmin.getSelectedItem().toString().split(" - ")[0] : "";
        String val_tglTransaksi = TglTransaksi.getText();
        String val_total = TotalPembayaran.getText();
              String val_pembeliid = PilihanNama.getSelectedItem() != null ? PilihanNama.getSelectedItem().toString().split(" - ")[0] : "";

        if (val_pembeliid.isEmpty() || val_adminid.isEmpty() || val_tglTransaksi.isEmpty() || val_total.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Semua data harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return; 
        }

        try {
            int id = Integer.parseInt(val_id);
            int pembeliid = Integer.parseInt(val_pembeliid);
            int adminid = Integer.parseInt(val_adminid);

            Transaksi transaksi = new Transaksi(
                0,
                pembeliid,
                adminid,
                val_tglTransaksi,
                val_total 
            );

            Transaksi.InsertTransaksi(transaksi);
            
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            
            loadDataTransaksi(); 
            loadPilihanPembeli();
            loadPilihanAdmin();
            
            IdTransaksi.setText("");
            TglTransaksi.setText("");
            TotalPembayaran.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ID, Pembeli ID, dan Admin ID harus berupa angka", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat menambahkan data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButtonTambahActionPerformed

    private void TotalPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalPembayaranActionPerformed

    private void ButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditActionPerformed
        // TODO add your handling code here:
        int selectedRow = TabelTransaksi.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih Baris yang akan diubah", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Object idValue = modeltransaksi.getValueAt(selectedRow, 0);

        if (idValue == null || idValue.toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ID tidak valid atau kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int id = Integer.parseInt(idValue.toString()); 
            int kategori1 = Integer.parseInt(PilihanNama.getSelectedItem().toString().split(" - ")[0]);
            String tgl_transaksi = TglTransaksi.getText();
            String total = TotalPembayaran.getText();
            int kategori2 = Integer.parseInt(PilihanAdmin.getSelectedItem().toString().split(" - ")[0]);

            Transaksi transaksi = new Transaksi(id, kategori1, kategori2, tgl_transaksi, total);

            try {
                
                Transaksi.updateTransaksi(transaksi);
                
                JOptionPane.showMessageDialog(null, "Data berhasil diubah", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                loadDataTransaksi();
                loadPilihanPembeli();
                loadPilihanAdmin();
                
                IdTransaksi.setText("");
                TglTransaksi.setText("");
                TotalPembayaran.setText("");

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Tidak dapat mengubah data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ID atau kategori tidak valid: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButtonEditActionPerformed

    private void PilihanNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilihanNamaActionPerformed
        // TODO add your handling code here:
        if (PilihanNama.getSelectedItem() != null) {
        int pembeliId = Integer.parseInt(PilihanNama.getSelectedItem().toString().split(" - ")[0]);

        try (Connection connection = Transaksi.getConnection();
             PreparedStatement stmt = connection.prepareStatement("SELECT total FROM tb_pesankamar WHERE id = ?")) {
            
            stmt.setInt(1, pembeliId);
            ResultSet rs = stmt.executeQuery();
            
                if (rs.next()) {
                    String total = rs.getString("total");
                    TotalPembayaran.setText(total);
                } else {
                    TotalPembayaran.setText("0");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Gagal memuat total: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_PilihanNamaActionPerformed

    private void ButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapusActionPerformed
        // TODO add your handling code here:
        int selectedRow = TabelTransaksi.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih Baris yang akan dihapus", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = (int) modeltransaksi.getValueAt(selectedRow, 0);

        try {
            Transaksi.deleteTransaksi(id);
            loadDataTransaksi();
            loadPilihanPembeli();
            loadPilihanAdmin();
            
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat menghapus data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButtonHapusActionPerformed

    private void IdTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdTransaksiActionPerformed

    private void ButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResetActionPerformed
        // TODO add your handling code here:
        IdTransaksi.setText("");
        PilihanNama.setSelectedIndex(0);
        PilihanAdmin.setSelectedIndex(0);
        TglTransaksi.setText("");
        TotalPembayaran.setText("");
    }//GEN-LAST:event_ButtonResetActionPerformed

    private void PilihanAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilihanAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PilihanAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void loadDataAdmin() {
        modeladmin.setRowCount(0);
        try {
            List<TambahAdmin> list_admin = Admin.getAllAdmin();
            
            for (TambahAdmin brg: list_admin) {
                modeladmin.addRow(
                    new Object[]{
                       brg.getId(),
                       brg.getNamaAdmin(),
                       brg.getRole(),
                       brg.getTglBergabung()
                    }
            );
        }
            
        TabelAdmin.setModel(modeladmin);
        
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat memuat data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void loadDataPemesanan() {
        model1.setRowCount(0);
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_penginapan", "root", "");

            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM tb_pesankamar");

            while (rs.next()) {
                String tipeKamar = rs.getString("tipe_kamar");
                String nama = rs.getString("nama_pembeli");
                String nomorHp = rs.getString("nomor_hp");
                String jumlahOrang = rs.getString("jumlah_orang");
                String checkin = rs.getString("tgl_checkin");
                String checkout = rs.getString("tgl_checkout");
                String membership = rs.getString("membership");
                String total = rs.getString("total");

                model1.addRow(new Object[]{tipeKamar, nama, nomorHp, jumlahOrang, checkin, checkout, membership, total});
            }

            rs.close();
            stmt.close();
            conn.close();
            
        } catch (SQLException e) {
            e.printStackTrace();
        }

        TabelPemesananPembeli.setModel(model1);
        }
    
    public void loadDataTransaksi() {
        modeltransaksi.setRowCount(0);
        try {
            List<Transaksi> list_transaksi = Transaksi.getAllTransaksi();
            
            for (Transaksi transaksi: list_transaksi) {
                modeltransaksi.addRow(
                    new Object[]{
                       transaksi.getId(),
                       transaksi.getPembeliId(),
                       transaksi.getAdminId(),
                       transaksi.getTglTransaksi(),
                       transaksi.getTotal()
                    }
            );
        }
        
        TabelTransaksi.setModel(modeltransaksi);
        
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat memuat data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void loadPilihanPembeli() {
        PilihanNama.removeAllItems();
        try (Connection connection = Transaksi.getConnection();
             Statement stmt = connection.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT id, nama_pembeli FROM tb_pesankamar")) {

            while (rs.next()) {
                int id = rs.getInt("id");
                String nama = rs.getString("nama_pembeli");
                PilihanNama.addItem(id + " - " + nama); 
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat daftar pembeli: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void loadPilihanAdmin() {
    PilihanAdmin.removeAllItems();
    try (Connection connection = Transaksi.getConnection();
        Statement stmt = connection.createStatement();
        ResultSet rs = stmt.executeQuery("SELECT id, nama_admin FROM tb_admin")) {
        
            while (rs.next()) {
                int id = rs.getInt("id");
                String nama = rs.getString("nama_admin");
                PilihanAdmin.addItem(id + " - " + nama);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat daftar admin: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void updatePilihan() {
    int selectedRow = TabelTransaksi.getSelectedRow();
    if (selectedRow == -1) {
        return; 
    }

    Object idPembeliObj = modeltransaksi.getValueAt(selectedRow, 1); 
    Object idAdminObj = modeltransaksi.getValueAt(selectedRow, 2);   

    if (idPembeliObj != null && idAdminObj != null) {
        int idPembeli = Integer.parseInt(idPembeliObj.toString());
        int idAdmin = Integer.parseInt(idAdminObj.toString());
        
        // Pilihan Pembeli
        for (int i = 0; i < PilihanNama.getItemCount(); i++) {
            String item = PilihanNama.getItemAt(i);
            if (item.startsWith(idPembeli + " - ")) {
                PilihanNama.setSelectedIndex(i);
                break;
            }
        }
        
        // Pilihan Admin
        for (int i = 0; i < PilihanAdmin.getItemCount(); i++) {
            String item = PilihanAdmin.getItemAt(i);
            if (item.startsWith(idAdmin + " - ")) {
                PilihanAdmin.setSelectedIndex(i);
                break;
            }
        }
    }
}

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEdit;
    private javax.swing.JButton ButtonHapus;
    private javax.swing.JButton ButtonReset;
    private javax.swing.JButton ButtonTambah;
    private javax.swing.JButton EditAdmin;
    private javax.swing.JButton HapusAdmin;
    private javax.swing.JButton HapusPemesanan;
    private javax.swing.JTextField IdAdmin;
    private javax.swing.JTextField IdTransaksi;
    private javax.swing.JTextField NamaAdmin;
    private javax.swing.JComboBox<String> PilihanAdmin;
    private javax.swing.JComboBox<String> PilihanNama;
    private javax.swing.JButton ResetFormAdmin;
    private javax.swing.JTextField RoleAdmin;
    private javax.swing.JTable TabelAdmin;
    private javax.swing.JTable TabelPemesananPembeli;
    private javax.swing.JTable TabelTransaksi;
    private javax.swing.JTextField TglAdmin;
    private javax.swing.JTextField TglTransaksi;
    private javax.swing.JTextField TotalPembayaran;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
